#
#
#
#
#
{0}{}{Spieloptionen}
{1}{}{Bildoptionen}

{50}{}{Bildoptionen}
{51}{}{Benutzerdefiniert}
{52}{}{BREITE}
{53}{}{HÖHE}
{54}{}{Fertig}
{55}{}{Abbrechen}
{56}{}{Fallout muss neu gestartet werden.}
{57}{}{Möchten Sie nun Fallout neustarten?}
{58}{}{ja}
{59}{}{nein}
{60}{}{}

{100}{}{Hi-Res}
{101}{}{AUFLÖSUNG}
{102}{}{Farben}
{103}{}{8-Bit}
{104}{}{16-Bit}
{105}{}{32-Bit}
{106}{}{SIDE-BAR ÄNDERN}
{107}{}{Liste umkehren}
{108}{}{Fenstermodus}
{109}{}{Scroll-Taste zuweisen}
{110}{}{Skalierung X2}
{111}{}{Bildwiederholrate}

{130}{}{Fenstermodus-Taste}
{131}{}{Ausw.}
{132}{}{Name}

{140}{}{Grafikmodus:}
{141}{}{Einfach}
{142}{}{Sfall DirectX 9-Modus:}
{143}{}{}

{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}

{147}{}{Direct3D 9}
{148}{}{Vertex Hardware Processing:}
{149}{}{Shader Version 2.0:}

{150}{}{Pannel-Skalierung}
{151}{}{1}
{152}{}{2}
{153}{}{3}

{154}{}{Filme}
{155}{}{Begrüßung}
{156}{}{Hilfe}
{157}{}{Tot}
{158}{}{End-Dias}
{159}{}{Hauptmenü}

{200}{}{Sfall}
{201}{}{SKALIERUNG AUF:}
{202}{}{DX-9-MODUS}
{203}{}{Aus}
{204}{}{Vollbild}
{205}{}{Fenster}
{206}{}{GPU-Blitting}
{207}{}{This setting has no effect while in Basic Graphics Mode.}

{250}{}{Ignoriere PC-Scroll-Limit}
{253}{}{Pfadfindung-Reichweite}
{254}{}{Normal}
{255}{}{Max}
{256}{}{Nebel des Krieges einschalten}
{257}{}{Nebel-Sichtweite}
{258}{}{Dunkel}
{259}{}{Heller}

{300}{}{EINE TASTE DRÜCKEN, oder mit ESC abbrechen.}

{500}{}{Auflösungspatch-Einstellungen.}
{501}{}{Einstellungen für Auflösung, Farbtiefe und Bildwiederholrate im Vollbildmodus.}
{502}{}{Einstellungen für Farbtiefe im Vollbildmodus.}
{503}{}{Einstellungen für die Bildwiederholrate im Vollbildmodus. Bei '0' wird die Treibereinstellung verwendet.}
{504}{}{Customize the Fullscreen Width by clicking the number box.}
{505}{}{Customize the Fullscreen Height by clicking the number box.}
{506}{}{Fenstermodus ein- oder ausschalten.}
{507}{}{In Window Mode, this is the key you will hold down when using the mouse to scroll the Game and World maps.}
{508}{}{Press the red button to select a different key. Or click the number box to edit the Windows Virtual key code.}
{509}{}{The name of the currently selected key.}
{510}{}{Enable X2 scaling. This will also up the min res to 1280x960. With Window mode requiring more space for its frame.}
{511}{}{Nebel des Krieges ein- oder ausschalten. For best results this should be enabled before entering a map for the first time.}
{512}{}{Adjust the light level and the Mouse 'look at' visibility of floors, walls and scenery under the fog.}
{513}{}{Floors, walls and scenery will always be visible and Mouse "look at" will function normally.}
{514}{}{Floors, walls and scenery will be darkened and unresponsive to Mouse "look at" until discovered.}
{515}{}{When enabled, scrolling away from the Player Character is unlimited. This works well if Fog Of War enabled.}
{516}{}{Increase the number of search nodes to extend the path finding distance. 20 levels in 2000 node increments.}
{517}{}{2000 path search nodes (original value). Note: Extra nodes may have unforeseen effects, see Readme.}
{518}{}{40 000 path search nodes. Note: Extra nodes may have unforeseen effects, see Readme for further details.}
{519}{}{Anpassung, wie die Bilder dargestellt werden sollen.}
{520}{}{Originale Größe.}
{521}{}{Streckt das Bild auf die richige Größe. Das originale Seitenverhältnis wird mitberücksichtigt.}
{522}{}{Streckt das Bild. Anmerkung: Sind Untertitel eingeschaltet, wird unten Platz für die Untertitel freigehalten.}
{523}{}{Click below to cycle the in-game interface Side Bar options.}
{524}{}{Apply any changes and Exit.}
{525}{}{Exit without saving.}


