{100}{}{Ein Mann in einer Powerrüstung.}
{101}{}{Arthur, Sohn von Uther Pendragon.}
{102}{}{Sein Hosenschlitz ist offen.}
{103}{}{Heil Euch, Reisender. Ich bin Arthur, Sohn von Uther Pendragon, von der Brotherhood of Steel. Wir sind auf der Suche nach der Heiligen Handgranate von Antiochien. Habt Ihr sie gesehn?}
{104}{}{Heilige was von wem?}
{105}{}{Spielerantwort}
{106}{}{Öhm.}
{107}{}{Keine Zeit zum Reden. Wir sind auf der Suche.}
{108}{}{Wir suchen die Heilige Handgranate von Antiochien.}
{109}{}{Für die Brotherhood of Steel!}
{110}{}{Hmm... Afrikanische oder europäische Schwalbe?}
{111}{}{He! Das ist nicht euers, oder?}
{112}{}{Ich warne Euch. Nehmt Eure Pfoten da weg.}
{113}{}{Jetzt reicht's. Genug ist genug.}
{114}{}{Die heilige Handgranate von Antiochien? Natürlich, weil sie die tollste gegen Menschen gerichtete Wurfwaffe ihrer Art ist.}
{115}{}{Warum sucht ihr nach einer solch schrecklichen Waffe?}
{116}{}{Wir, von der Brotherhood of Steel, möchten diese so vernichtende Waffe unserer Vorfahren finden und sie vor denen schützen, die die Macht der heiligen Handgranate von Antiochien mißbrauchen würden.}
{117}{}{Warum?}
{118}{}{Na... weil die Brotherhood of Steel sich geschworen hat, die Schwachen und Schutzlosen zu schützen und dieses Ding könnte wirklich jemanden verletzen.}
{119}{}{Warum?}
{120}{}{Hmm... weil es die einzig moralische Wahl ist.}
{121}{}{Warum?}
{122}{}{Wei... hm... Ihr seht ja, wir sind ziemlich beschäftigt. Helft Ihr uns jetzt, oder nicht? Habt Ihr die heilige Handgranate von Antiochien gesehen, oder nicht?}
{123}{}{Ja.}
{124}{}{Nein.}
{125}{}{Ja, warum denn nicht gleich? Wenn Ihr uns nur noch schnell sagen könntet, wo, sind wir auch schon weg und Ihr könnt mit dem weitermachen, was Ihr vorher gemacht habt.}
{126}{}{[Du zeigst in eine beliebige Richtung.]}
{127}{}{Alsdann. Danke für Eure Hilfe. Hier ist etwas für Eure Mühe.}
{128}{}{Warte! Ich bin auch auf der Suche. Ich suche das heilige GECK. Habt Ihr es gesehen?}
{129}{}{Na dann können wir diese Unterhaltung ja beenden. Wir brechen auf.}
{130}{}{[Ende]}
{131}{}{Blutrünstiger Polet!}
{132}{}{[Ende]}
{133}{}{GECK sagtet Ihr? Natürlich ja, wir haben zwei davon. Brauchen nicht noch eins. Dennoch danke.}
{134}{}{Nachdem ihr ja zwei habt, könntet ihr mir ja vielleicht eins geben.}
{135}{}{Nein. Nein. Das können wir nicht. Es wäre falsch Eure Suche so leicht zu beenden. In der Richtung gibt's noch mehr davon. Holt Euch euer eigenes. [Er deutet in ungefähr dieselbe Richtung, in die du gezeigt hast, als du ihm sagtest, wo die heilige Handgranate von Antiochien ist.]}
{136}{}{[Ende]}

{200}{}{Sprecht Ihr die Sprache des Königs?}
{201}{}{Hallooo.}
{202}{}{He, ich bin hier drüben.}
{203}{}{Wenn Ihr einen Augenblick Zeit hättet.}
{204}{}{Ähem.}
{205}{}{Hey, ignorier mich nicht einfach.}
{206}{}{Biiiiiiiitte! Ich muß Euch was Wichtiges fragen.}

{207}{}{Na denn, wir müssen unsre Suche nach der Handgranate von Antiochien fortsetzen. Komm schon, Mathias.}

#added by killap - RP 1.3
{300}{}{Unsere Aufgabe ist erfüllt!}
{301}{}{Arthur, zu euren Diensten.}