{100}{}{Du siehst einen Mann, der wenig Kleidung trägt.}
{101}{}{Du siehst Kaga.}
{103}{}{Er trägt eine Hose und sieht aus, als wenn er aus deinem Stamm käme.}
{104}{}{Ich sollte das "Auserwählte Wesen" sein!}
{105}{}{Wie konnten Sie es nur wagen, mich aus dem Dorf zu verbannen.}
{106}{}{Ich werde mich an dir rächen!}
{107}{}{Kaga wird dich in dein nächstes Leben befördern!}
{108}{}{Wir werden uns wiedersehen!}
{109}{}{Ich wurde noch nie zuvor besiegt!}
{110}{}{Ich werde es zu meinem Ziel machen, dich zu vernichten.}

#added by RP 1.3
{150}{}{[Ein großer, kräftiger Krieger steht vor dir. Seine Augen glänzen hasserfüllt, als er dich ansieht.] So, erst vertreiben sie Kaga und jetzt sollst du das "Auserwählte Wesen" sein? Ha! Die glauben wirklich, dass du was besonderes bist; das Enkelkind des Vaultbewohners. Du glaubst, du bist besser als ich, Kaga der Große?!}
{151}{}{Sicher, ich BIN das "Auserwählte Wesen", oder?}
{152}{}{Hey, warte mal 'ne Sekunde. Ich hab nie behauptet, dass ich etwas besonderes bin.}

{160}{}{Dieser Titel bedeutet gar nichts, wenn Kaga dir den Kopf von den Schultern reißt!} 
{161}{}{Deine Worte sind wie Schall und Rauch. Mit deinem Tod wird meine Ehre wiederhergestellt. Kaga bekommt jetzt endlich seine Rache!}

#dumb dialogue
{200}{}{Ggrrr?}
{201}{}{Was!? Du bist das neue "Auserwählte Wesen"? Oh man, sie müssen echt verzweifelt sein.}
{202}{}{Dich nicht mögen. Du sehen aus schlecht.}
{203}{}{Beenden wir das Geplänkel. Bereite dich darauf vor, durch die Hand von Kaga zu sterben!}
