{100}{}{Du siehst einen Mann in einer Metallrüstung.}
{101}{}{Du siehst Kaga.}
{102}{}{Jepp, es ist Kaga "Der nicht so Große". Er besitzt nun eine Metallrüstung und will dich töten.}
{103}{}{Du schon wieder!}
{104}{}{Ich habe unsere ermüdenden Treffen langsam satt.}
{105}{}{Das "Auserwählte Wesen" - Pah!}
{106}{}{Bringen wir es endlich hinter uns.}
{107}{}{Du wirst es bereuen, jemals den Namen Kaga gehört zu haben!}
{108}{}{Meine Fähigkeiten haben sich seit unserem letzten Zusammentreffen verbessert.}
{109}{}{Das scheint wohl eine schlechte Angewohnheit von dir zu werden.}
{110}{}{Kaga muss noch ein bisschen trainieren.}
{111}{}{Kaga wird wiederkommen.}

{120}{}{Also treffen wir uns wieder, Kaga.}

#added by RP 1.3
{150}{}{[Ein großer, kräftiger Krieger steht vor dir. Seine Augen glänzen hasserfüllt, als er dich ansieht.] So, erst vertreiben sie Kaga und jetzt sollst du das "Auserwählte Wesen" sein? Ha! Die glauben wirklich, dass du was besonderes bist; das Enkelkind des Vaultbewohners. Du glaubst, du bist besser als ich, Kaga der Große?!}
{151}{}{Sicher, ich BIN das "Auserwählte Wesen", oder?}
{152}{}{Hey, warte mal 'ne Sekunde. Ich hab nie behauptet, dass ich etwas besonderes bin.}

{160}{}{Dieser Titel bedeutet gar nichts, wenn Kaga dir den Kopf von den Schultern reißt!} 
{161}{}{Deine Worte sind wie Schall und Rauch. Mit deinem Tod wird meine Ehre wiederhergestellt. Kaga bekommt jetzt endlich seine Rache!}

#dumb dialogue
{200}{}{Ggrrr?}
{201}{}{Was!? Du bist das neue "Auserwählte Wesen"? Oh man, sie müssen echt verzweifelt sein.}
{202}{}{Dich nicht mögen. Du sehen aus schlecht.}
{203}{}{Beenden wir das Geplänkel. Bereite dich darauf vor, durch die Hand von Kaga zu sterben!}
