{100}{}{Du siehst einen Mann in einer modernen Powerrüstung. Er sieht nicht freundlich aus.}
{101}{}{Du siehst Kaga, der eine moderne Powerrüstung trägt.}
{102}{}{Ein großes Stück Metall mit Armen und Waffen.}
{103}{}{Ich werde der Verfolgung müde. Lass es uns beenden.}
{104}{}{Das ist das letzte Mal, dass wir uns treffen werden, Kaga.}
{105}{}{Du bist keine Herausforderung für Kaga!}
{106}{}{Ich freue mich darauf, dich endlich in dein nächstes Leben zu schicken.}
{107}{}{Du wirst ein würdiger Gegner sein.}
{108}{}{Dieser Teil des Ödlands braucht keinen Weltverbesserer wie dich!}
{109}{}{Nachdem ich dich getötet habe, werde ich die am meisten gefürchtete Person in diesem Teil des Ödlands sein.}
{110}{}{Ich freue mich schon darauf, nach Arroyo zurückzukehren - um es nieder zu brennen!!!}
{111}{}{Kaga wird berühmt sein, wenn er dich getötet hat.}

{120}{}{Kagaaaaaaaa!}

#added by RP 1.3
{150}{}{[Ein großer, kräftiger Krieger steht vor dir. Seine Augen glänzen hasserfüllt, als er dich ansieht.] So, erst vertreiben sie Kaga und jetzt sollst du das "Auserwählte Wesen" sein? Ha! Die glauben wirklich, dass du was besonderes bist; das Enkelkind des Vaultbewohners. Du glaubst, du bist besser als ich, Kaga der Große?!}
{151}{}{Sicher, ich BIN das "Auserwählte Wesen", oder?}
{152}{}{Hey, warte mal 'ne Sekunde. Ich hab nie behauptet, dass ich etwas besonderes bin.}

{160}{}{Dieser Titel bedeutet gar nichts, wenn Kaga dir den Kopf von den Schultern reißt!} 
{161}{}{Deine Worte sind wie Schall und Rauch. Mit deinem Tod wird meine Ehre wiederhergestellt. Kaga bekommt jetzt endlich seine Rache!}

#dumb dialogue
{200}{}{Ggrrr?}
{201}{}{Was!? Du bist das neue "Auserwählte Wesen"? Oh man, sie müssen echt verzweifelt sein.}
{202}{}{Dich nicht mögen. Du sehen böse aus.}
{203}{}{Beenden wir das Geplänkel. Bereite dich darauf vor, durch die Hand von Kaga zu sterben!}
