{100}{}{Du siehst einen Mann in einer Kampfrüstung.}
{101}{}{Du siehst den verdammten Kaga in einer Kampfrüstug.}
{102}{}{Das glaube ich jetzt nicht... Kaga hat nun eine Kampfrüstung und scheint einige anständige Waffen zu besitzen.}
{103}{}{Diesmal bin ich vorbereitet!}
{104}{}{Das "Auserwählte Wesen" wird niemals nach Arroyo zurückkehren!}
{105}{}{Kaga wird dich zerquetschen!}
{106}{}{Kaga fürchtet niemanden!}
{107}{}{Stillhalten, damit Kaga einen guten Treffer landen kann.}
{108}{}{Wir werden uns wiedersehen!}
{109}{}{Dies ist nicht das letzte Mal, dass du Kaga sehen wirst.}
{110}{}{Kaga braucht definitiv mehr Training.}

{120}{}{Verschwinde Kaga!}

#added by RP 1.3
{150}{}{[Ein großer, kräftiger Krieger steht vor dir. Seine Augen glänzen hasserfüllt, als er dich ansieht.] So, erst vertreiben sie Kaga und jetzt sollst du das "Auserwählte Wesen" sein? Ha! Die glauben wirklich, dass du was besonderes bist; das Enkelkind des Vaultbewohners. Du glaubst, du bist besser als ich, Kaga der Große?!}
{151}{}{Sicher, ich BIN das "Auserwählte Wesen", oder?}
{152}{}{Hey, warte mal 'ne Sekunde. Ich hab nie behauptet, dass ich etwas besonderes bin.}

{160}{}{Dieser Titel bedeutet gar nichts, wenn Kaga dir den Kopf von den Schultern reißt!} 
{161}{}{Deine Worte sind wie Schall und Rauch. Mit deinem Tod wird meine Ehre wiederhergestellt. Kaga bekommt jetzt endlich seine Rache!}

#dumb dialogue
{200}{}{Ggrrr?}
{201}{}{Was!? Du bist das neue "Auserwählte Wesen"? Oh man, sie müssen echt verzweifelt sein.}
{202}{}{Dich nicht mögen. Du sehen aus schlecht.}
{203}{}{Beenden wir das Geplänkel. Bereite dich darauf vor, durch die Hand von Kaga zu sterben!}
