{100}{}{Du siehst einen Mann in einer Lederrüstung.}
{101}{}{Du siehst Kaga.}
{102}{}{Er trägt eine Lederrüstung und hat die Unsitte bei einer Unterhaltung über sich selbst in der dritten Person zu Sprechen.}
{103}{}{Das wird das letzte Mal sein, dass du Kaga siehst.}
{104}{}{Nachdem dich Kaga getötet hat, wird er Arroyo niederbrennen.}
{105}{}{Fühle den Zorn des Kaga!}
{106}{}{Ich bin der große Kaga!}
{107}{}{Kaga wird von allen gefürchtet.}
{108}{}{Kaga wird deinen Kopf als Trophäe behalten.}
{109}{}{Gib auf und dein Tod wird kurz sein.}
{110}{}{Kaga wird zurückkommen!}
{111}{}{Du kannst den großen Kaga nicht töten!}
{112}{}{Du hast Glück, dass Kaga woanders geschäftliche Dinge zu erledigen hat.}
{113}{}{Kaga wird dich wiedertreffen.}

{120}{}{Es ist wieder dieser Typ namens Kaga.}

#added by RP 1.3
{150}{}{[Ein großer, kräftiger Krieger steht vor dir. Seine Augen glänzen hasserfüllt, als er dich ansieht.] So, erst vertreiben sie Kaga und jetzt sollst du das "Auserwählte Wesen" sein? Ha! Die glauben wirklich, dass du was besonderes bist; das Enkelkind des Vaultbewohners. Du glaubst, du bist besser als ich, Kaga der Große?!}
{151}{}{Sicher, ich BIN das "Auserwählte Wesen", oder?}
{152}{}{Hey, warte mal 'ne Sekunde. Ich hab nie behauptet, dass ich etwas besonderes bin.}

{160}{}{Dieser Titel bedeutet gar nichts, wenn Kaga dir den Kopf von den Schultern reißt!} 
{161}{}{Deine Worte sind wie Schall und Rauch. Mit deinem Tod wird meine Ehre wiederhergestellt. Kaga bekommt jetzt endlich seine Rache!}

#dumb dialogue
{200}{}{Ggrrr?}
{201}{}{Was!? Du bist das neue "Auserwählte Wesen"? Oh man, sie müssen echt verzweifelt sein.}
{202}{}{Dich nicht mögen. Du sehen aus schlecht.}
{203}{}{Beenden wir das Geplänkel. Bereite dich darauf vor, durch die Hand von Kaga zu sterben!}
