# QUICK LOOK
{100}{}{Du siehst eine Fluffer.}

# 1. LOOK (PLAYER IS MALE)
{150}{}{Du siehst eine halbwegs attraktive Frau. Sie scheint dich abzuschätzen.}
{151}{}{Du siehst eine Fluffer. Sie scheint sich zu fragen, ob sie sich um dich kümmern soll oder nicht.}

# 2. LOOK (PLAYER IS FEMALE)
{160}{}{Du siehst eine halbwegs attraktive Frau. Sie sieht dich an, als ob du eine Rivalin wärst.}
{161}{}{Du siehst eine Fluffer. Sie sieht dich an, als ob du eine Rivalin wärst.}

# 3. [ENCLAVE DESTROYED]
{200}{}{Oh mein G… Er ist es. } 
{201}{}{Du bist der größte Hengst der Welt.}
{200}{}{::KICHER::} 
{203}{}{Wie ich höre, suchen die Brüder nach dir. Die wollen 'nen Film über dein Abenteuer drehen.}
{204}{}{Yeah, }
{205}{}{::Klatsch::}
{206}{}{::Jubel::}
{207}{}{Oh mein G… Sie ist es. }
{208}{}{Weg da, Mädel!}
{209}{}{::Daumen hoch::}

# 4. [POWER ARMOR]
{225}{}{Kommt gar nicht in Frage. Mit dem Ding nicht. NIEMALS.}
{226}{}{Wie zum Geier gehst du mit dem Ding ins Bad?}
{227}{}{Ist das etwa wie ein Vibrator?}
{228}{}{Ist das etwa ein neuartiges Ganzkörperkondom?}

# 5. [MALE, PORN STAR]
{235}{}{Brauchst du irgendwas, }
{236}{}{Hier drüben }
{237}{}{Da! Das ist er!}
{238}{}{Es ist }
{239}{}{Ich wünschte, ich könnte 'ne Szene mit dir machen, }
{240}{}{Dieser Mann bringt mich wirklich zum schmelzen.}
{241}{}{Er kann mir jeder Zeit 'ne Ladung verpassen.}
{242}{}{Du böse kleine Schlange - bleib schön hier.}

# 6. [PORN STAR, FEMALE]
{245}{}{Brauchst du irgendwas, }
{246}{}{Wenn ich mich heute um noch einen Schauspieler kümmern muss, geh ich 'ne Runde kotzen.}
{247}{}{Gar nicht so einfach, 'ne Fluffer zu sein.}
{248}{}{Ich hörte, dass die Lage zwischen den Familien wieder angespannt ist.}
{249}{}{Letzte Woche trat ich in Jules Kronjuwelen.}
{250}{}{Ich wünschte, die Brüder würden mich schauspielern lassen.}
{251}{}{Ich habe keine Ahnung, was die Korsischen Brüder an IHR sehen…}

# 7. [MALE, PRIZEFIGHTER]
{255}{}{Oh mein G… Er ist es. }
{256}{}{Sieh dir diese Muskeln an! Da werde ich ganz schwach…}
{257}{}{Er ist wie ein Panzer gebaut. Schaut euch die Kanone an.}
{258}{}{Schaut euch die Kanone vom Panzer an…}
{259}{}{Er gehört mir ganz alleine…}
{260}{}{::Seufz::}
{261}{}{Dieser Mann bringt mich wirklich zum schmelzen.}
{262}{}{Du böse kleine Schlange - bleib schön hier.}

# 8. [FEMALE, PRIZEFIGHTER]
{270}{}{Oh mein G… Sie ist es. }
{271}{}{Willkommen im Studio, meine Dame.}
{272}{}{Sie sieht so… [schüttelt sich] …gefährlich aus.}
{273}{}{Sie ist sehr sexy.}
{274}{}{Hallo meine Dame. Lass es mich wissen, wenn ich dir behilflich sein kann.}

# 9. [MALE, MADE MAN/BERSERKER]
{280}{}{Oh mein G… Er ist es. }
{281}{}{Willkommen im Studio, mein Herr.}
{282}{}{Er sieht so… [schüttelt sich] …gefährlich aus.}
{283}{}{Das ist einer der härtesten Typen, den ich je gesehen habe.}
{284}{}{Dieser Mann bringt mich wirklich zum schmelzen.}
{285}{}{Du böse kleine Schlange - bleib schön hier.}

# 10. [FEMALE, MADE MAN/BERSERKER]
{290}{}{Oh mein G… Sie ist es. }
{291}{}{Willkommen im Studio, meine Dame.}
{292}{}{Sie sieht so… [schüttelt sich] …gefährlich aus.}
{293}{}{Sie ist sehr sexy.}
{294}{}{Hallo meine Dame. Lass es mich wissen, wenn ich dir behilflich sein kann.}

# 11. [MALE, NO REP + MYRON]
{300}{}{Oh, Mist! Es ist Myron! Lauf!}
{301}{}{Mist! Es ist Myron. Ruhig bleiben… Er kann Angst riechen.}
{302}{}{Du solltest Myron besser von mir fernhalten.}
{303}{}{Myron, du hälst Abstand, so breit wie die HÖLLE, von mir.}
{304}{}{Wenn Myron hier anfängt zu arbeiten, dann bin ich weg.}
{305}{}{Myron, hälst du nun länger als fünf Sekunden durch?}
{306}{}{Myron, verschwinde besser von hier, bevor dich die Brüder sehen.}

# 12. FLOAT/[LEATHER]
{315}{}{Wissen die Leder-Freaks immer noch nicht, dass sie nur mittwochs bedient werden?}
{316}{}{Spitze. Noch so 'n SM-Schauspieler.}
{317}{}{Oooooh, schwarzes Leder. Nun, DAS ist neu.}
{318}{}{Leder- oder Fessel-Einheiten sind bei uns erst nächste Woche dran.}
{319}{}{Toll, noch so ein Leder-Häschen.}
{320}{}{Leder-Häschen, das Casting ist am Mittwoch, verstanden?}

# 13. [NO REP + BONENOSE]
{325}{}{Wenn ich mich heute um noch einen Schauspieler kümmern muss, geh ich 'ne Runde kotzen.}
{326}{}{Ich hörte, dass die Lage zwischen den Familien wieder angespannt ist.}
{327}{}{Der Typ mit dem Knochen in der Nase ist irgendwie süß. So auf 'ne sadomasochistische Art.}
{328}{}{Sieh dir den Wilden mit dem Knochen in der Nase gut an. Der bringt's noch mal weit.}
{329}{}{Na toll. NOCH 'ne Fluffe. So wie die aussieht, arbeitet die bestimmt für den halben Preis.}
{330}{}{Wer ist der Typ da mit dem Knochen in der Nase?}
{331}{}{Schaut euch den Wilden mit dem Knochen in der Nase an. Er kam von weit her.}
{332}{}{Wow. Ich hab schon viele Unfälle am Set gesehen, aber niemals einen Typen, dem ein Knochen an der Nase hing.}
{333}{}{Ich wünschte, die Brüder würden mich schauspielern lassen.}
{334}{}{::Glares at you::}
{335}{}{Na toll. NOCH 'ne Mieze. So wie die aussieht, arbeitet die bestimmt für den halben Preis.}
{336}{}{Wer ist die denn?}
{337}{}{Wer bist du denn?}

# 14. [NO REP]
{345}{}{Wenn ich mich heute um noch einen Schauspieler kümmern muß, muß ich mich übergeben.}
{346}{}{Gar nicht so einfach, 'ne Mieze zu sein.}
{347}{}{I hear the Families are getting tense again.}
{348}{}{I kicked Jules in his family jewels last week.}
{349}{}{Ich wünschte, die Brüder würden mich schauspielern lassen.}
{350}{}{Na toll. NOCH 'ne Mieze. So wie die aussieht, arbeitet die bestimmt für den halben Preis.}
{351}{}{::Glares at you::}
{352}{}{Wer ist die denn?}
{353}{}{Wer bist du denn?}

# 15. [ENCLAVE DESTROYED]
{360}{}{Die Enklave? Präsident? Erzähl mir die ganze Geschichte.}
{361}{}{Tom French scripted me. He has soft, gentle hands.}
{362}{}{They were still fighting the WAR?! Really! Good thing you wasted those bastards.}
{363}{}{You are a total badass. I mean, you start from a simple spear-chucking tribal - no offense - and go on to save the whole world. You kick ass. End of story.}
{365}{}{Erzähl mir alles über deinen Kampf gegen die Enklave... ich hol dir 'n kaltes Bier.}
{366}{}{I hear the Brothers are looking for you. They want to do a film based on your adventure.}

# 16. [PORN STAR]
{370}{}{Ooops. I dropped something in your pants. Let me get it.}
{371}{}{Ähm, du möchtest nicht zufällig einen saufen gehen, oder? Und wie wär's mit 'nem bißchen Liebe?}
{372}{}{How do you keep so fit?}
{373}{}{Can I have your autograph? On my chest?}
{374}{}{You being helped, }
{375}{}{I'll need some help with that barrel of yours.}
{376}{}{I hear you're very…hard to work with.}
{377}{}{I heard you cop an attitude, then you cop a feel. Fine by me.}
{378}{}{I'm really happy to know you! I mean, wow, you're }
{379}{}{Um, I know there's no filming going on, but do you need a fluffer anyway?}
{380}{}{Need someone to take care of that for you?}
{381}{}{Need a moist towelette, }
{382}{}{I loved you in Great Balls for Hire.}
{383}{}{I loved you in Good Will Humping.}
{384}{}{You were great in Pokeahotass.}
{385}{}{You were great in Vault Sexteen. Inspired, even.}
{386}{}{I haven't seen the Brothers around…try the office, maybe?}
{387}{}{Any chance you could talk the Corsican Brothers into letting me act?}
{388}{}{Fluffers have the important job of keeping the actors hard.}
{389}{}{Could I act in your next movie?}
{390}{}{I don't want to be a fluffer all my life. No, really.}
{391}{}{I'm just doing this to pay for school.}
{392}{}{My boyfriend doesn't know I work here.}
{393}{}{Hum job? I'll tell you about them some other time.}
{394}{}{My boyfriend doesn't know I work here.}
{395}{}{I wish some of the actors would shower. I mean a regular shower.}
{396}{}{I really want to act.}
{397}{}{My girlfriend doesn't know I work here.}
{398}{}{Gibst du mir ein Autogramm?}
{399}{}{Ähm, du möchtest nicht zufällig einen saufen gehen, oder? Wenn du an Frauen interessiert bist, heißt das.}
{400}{}{::Ignores you::}

# 17. [PRIZEFIGHTER]
{420}{}{Möchtest du mit mir in den Ring steigen, Champion?}
{421}{}{Nice unit you got there.}
{422}{}{Need someone to take care of that for you, champ?}
{423}{}{Getting out of boxing and into porn? Same thing, different stage.}
{424}{}{Are you getting into the business, too? Welcome aboard, champ.}
{425}{}{Getting into the business? Well, at least you won't have to start where I am.}
{426}{}{Me? I'm a fluffer. Sometimes.}
{427}{}{Fluffers have the important job of keeping the actors hard.}
{428}{}{The Brothers say I'm in-valuable. That's why they sleep with me so much.}
{429}{}{You should go into porn. You got the body for it.}
{430}{}{Wanna box?}
{431}{}{Hum job? I'll tell you about them some other time.}
{432}{}{Watch out for the Masticator. He's a real jerk. He tried to bite my ear off once.}
{433}{}{Hallo, Lady. Kann ich dir helfen mit…*irgendwas?*}
{434}{}{Ähm, wenn du später noch ein bißchen Gesellschaft suchst, Lady…}
{435}{}{Do you want the usual, ma'am?}

# 18. [MADE MAN]
{450}{}{Hallo, der Herr. Kann ich dir helfen mit…*irgendwas?*}
{451}{}{If you're looking for a little company later…}
{452}{}{Do you want the usual, sir?}
{453}{}{Need someone to take care of that for you?}
{454}{}{Put in a good word with the boss for me?}
{455}{}{Are you thinking of getting into the business, too?}
{456}{}{You should go into porn. You got the body for it.}
{457}{}{Hum job? I'll tell you about them some other time.}
{458}{}{Hello, ma'am. Can I help you with…*anything?*}
{459}{}{Ähm, wenn du später noch ein bißchen Gesellschaft suchst, Lady…}
{460}{}{Do you want the usual, ma'am?}

# 19. [BONE-NOSE]
{465}{}{Nein danke. Ich könnte ja mit meinem Lippenstift mehr Spaß haben.}
{466}{}{You? Sorry, I'll NEVER be that desperate.}
{467}{}{Äh, überkompensiert dein Freund mit dem Knochen in der Nase vielleicht was?}
{468}{}{Hat dein Freund mit dem Knochen in der Nase 'ne Freundin?}
{469}{}{Dein Freund mit dem Knochen in der Nase ist irgendwie süß. So auf 'ne sadomasochistische Art.}
{470}{}{Wer ist denn dein süßer Freund mit dem Knochen in der Nase?}
{471}{}{Tell the tribal with the bone in his nose that he'll go far in this industry.}
{472}{}{Whoa, I've seen accidents on the set, but never a guy who got a bone caught in his nose.}
{473}{}{I haven't seen the Brothers around…try the office, maybe?}
{474}{}{Fluffers have the important job of keeping the actors hard.}
{475}{}{I really want to act.}
{476}{}{I don't want to be a fluffer all my life. No, really.}
{477}{}{My boyfriend doesn't know I work here.}
{478}{}{Are you being helped?}
{479}{}{If you're looking for a job, talk to the Brothers.}
{480}{}{I'm just doing this to pay for college.}
{481}{}{I'd bang Avellone for free.}
{482}{}{It's not that I don't want to talk to you, but...oh, wait that IS it.}
{483}{}{I need to lie down.}
{484}{}{Hum job? I'll tell you about them some other time.}
{485}{}{You don't have a problem with skin flicks, do you?}
{486}{}{You the new fluffer?}
{487}{}{Got a towel? One of the actors had an…accident.}
{488}{}{Just don't bite the actors, and you should do fine.}
{489}{}{I wish some of the actors would shower. I mean a regular shower.}
{490}{}{Ähm, bist du neu hier?}
{491}{}{Salzmilch? Man gewöhnt sich dran.}

# 20. [NO REP]
{500}{}{Nein danke. Ich könnte ja mit meinem Lippenstift mehr Spaß haben.}
{501}{}{You? Sorry, I'll NEVER be that desperate.}
{502}{}{I haven't seen the Brothers around…try the office, maybe?}
{503}{}{Fluffers have the important job of keeping the actors hard.}
{504}{}{I really want to act.}
{505}{}{I don't want to be a fluffer all my life. No, really.}
{506}{}{My boyfriend doesn't know I work here.}
{507}{}{Are you being helped?}
{508}{}{If you're looking for a job, talk to the Brothers.}
{509}{}{I'm just doing this to pay for college.}
{510}{}{I'd bang Avellone for free.}
{511}{}{It's not that I don't want to talk to you, but...oh, wait that IS it.}
{512}{}{I need to lie down.}
{513}{}{Hum job? I'll tell you about them some other time.}
{514}{}{You don't have a problem with skin flicks, do you?}
{515}{}{You the new fluffer?}
{516}{}{Got a towel? One of the actors had an…accident.}
{517}{}{Just don't bite the actors, and you should do fine.}
{518}{}{I wish some of the actors would shower. I mean a regular shower.}
{519}{}{Ähm, bist du neu hier?}
{520}{}{Salzmilch? Man gewöhnt sich dran.}

{1200}{}{. Ihr wißt schon - hat der Enklave in den Hintern getreten.}
{1204}{}{! Was 'ne Art, der Enklave eins überzuziehen!}
{1207}{}{. Ihr wißt schon - hat der Enklave in den Hintern getreten.}
{1235}{}{?}
{1236}{}{!}
{1238}{}{!}
{1239}{}{.}
{1245}{}{?}
{1255}{}{.}
{1270}{}{.}
{1280}{}{.}
{1290}{}{.}
{1374}{}{?}
{1378}{}{!}
{1381}{}{?}