{100}{}{Du siehst einen Krieger.}
{101}{}{Du siehst ein Mitglied des Stammes.}
{102}{}{Eines der wenigen verbliebenen Stammesmitglieder.}

{200}{}{Du bist hier nicht willkommen.}
{201}{}{Die Geister mögen dich nicht.}
{202}{}{Verschwinde, Außenweltler!}
{203}{}{Warum suchst du uns heim?}
{204}{}{Willkommen, Krieger.}
{205}{}{Du bist uns immer willkommen.}
{206}{}{Die Geister sehen dich als einer von uns an.}
{207}{}{Danke für deine Hilfe.}
{208}{}{Ich glaubte, alle Außenweltler wären böse. Dem ist nicht so...}
{209}{}{Lass das.}
{210}{}{Sklavenhändler sind bei uns nicht erwünscht!}

# PC has defeated the Enclave
{300}{}{Wir fühlen uns durch deine Anwesenheit geehrt, Held.}
{301}{}{Dein Sieg über die Enclave wird in den Legenden erzählt werden. Deine Ahnen sind stolz auf dich.}