{100}{}{}
{101}{}{Du siehst ein Mitglied des Stammes.}
{102}{}{Du siehst Marli.}
{103}{}{Du siehst einen Krieger mit einem mürrischen Gesichtsausdruck.}

{110}{}{Geh weg! Ich möchte nicht gestört werden, Fremder. Komm ein anderes mal.}
{111}{}{Jaja, wie auch immer.}

{112}{}{Hmpf... unverschämt einfach so fremdes Eigentum anzufassen. Derjenige kann froh sein, dass der Brunnen wieder funktioniert.}
{113}{}{Gern geschehen.}
{114}{}{Was auch immer.}

{120}{}{Hallo, was willst du?}
{121}{}{Ich sehe, dass du einige Schwierigkeiten mit dem Brunnen hast. Was genau ist kaputt?}

{130}{}{[Er verzieht das Gesicht.] Jemand hat das Seil gestohlen. Ich weiß nicht wer, aber ich würde denjenigen erwürgen, wenn ich es wüsste. Wir sind seitdem auf das Regenwasser angewiesen, doch das reicht bei weitem nicht. Wir brauchen ein neues Seil, um an das Wasser zu kommen. Ich nehme nicht an, dass du eines hast, Outsider?}
{131}{}{Nicht bei mir, Tut mir leid. Jedoch Reise ich viel herum, sodass ich wahrscheinlich eines für euch finden könnte.}
{132}{}{In der Tat, ich habe eines. Ich werde versuchen, denn Brunnen für euch zu reparieren.}
{133}{}{Nö, aber so schwer ist es nicht an ein Seil ranzukommen. Ich bin mir sicher, dass ihr das schafft. Tschüß.}

{140}{}{Und, hast du den Brunnen repariert?}
{141}{}{Nein, noch nicht.}
{142}{}{Seh ich so aus, als würde ich es reparieren? Du stehst doch die ganze Zeit an diesem scheiß Ding, du Dummkopf!}

{150}{}{Und, hast du den Brunnen repariert?}
{151}{}{Ja, das Seil ist dort wo es hingehört. Siehst du?}

{160}{}{[Er blickt kurz zum Brunnen, und kichert.] Was hilft ein Seil, wenn du keinen Eimer angebracht hast? Oder trinkt ihr Outsider indem ihr Wasser von einem nassen Seil leckt? [Er schüttelt den Kopf und murmelt etwas vor sich hin.] Schau, du musst nur den Eimer befestigen, dann werde ich dich dafür entlohnen!}
{161}{}{Okay.}
{162}{}{Wie wäre es, wenn *du* den Eimer anbringst und ich werd mal schauen, wie ich es verhindern kann, dir in den Arsch zu treten.}

{170}{}{Hast du den Eimer angebracht?}
{171}{}{Nein, noch nicht.}
{172}{}{*Sieht* es so aus, als hätte ich den Eimer angebracht?}

{180}{}{Und? Hast du den Brunnen repariert? Ist der Eimer angebracht?}
{181}{}{Ja, es ist alles fertig.}
{182}{}{...}

{190}{}{Gut. Du kannst dir nicht vorstellen, wie sehr es unseren Stamm helfen wird. Hier nimm dieses Geld! Ich fand es im Ödland, aber wir haben keine Verwendung dafür.}
{191}{}{Danke.}

{200}{}{Danke vielmals, der Brunnen funktioniert jetzt einwandfrei!}
{201}{}{Danke für deine Hilfe.}
{202}{}{Schön dich wiederzusehen.}

{210}{}{Du wirst uns nicht lebend bekommen, Sklavenhändler!}


{1000}{}{Du hast den Brunnen des Stammes repariert.}

#added in RP 1.3
{300}{}{Du brauchst dich nicht gleich so aufzuregen, ich werd's tun. [Er murmelt.] Verrückte Outsider...}
{301}{}{[Fertig]}

{310}{}{[Er sieht dich an, dann den Brunnen.] Nein.}
{311}{}{Dann sieht es wohl so aus, dass ich ihn nicht anbringe.}

{320}{}{Hörst du mir überhaupt zu? Ich hab dich gefragt, ob der Brunnen repariert ist.}
{321}{}{... [Du seufzt, dann deutest du auf den Brunnen.]}

{330}{}{[Er dreht sich und schaut auf den Brunnen, dann wieder zu dir.] Toll. Sieht so aus, als hättest du ihn repariert. Warum nicht gleich so? Egal, hier etwas Geld. Ich fand es im Ödland und wir haben keine Verwendung dafür.}
{331}{}{... [Du nimmst das Geld und haust ab.]}

# PC has beaten the Enclave
{2000}{}{Entschuldige wenn ich mich idiotisch verhalten habe, Held.}
{2001}{}{Sorry, I lost your sub-machine gun. That gecko be a fierce one.}

{400}{}{[As you're about to walk away, Marli looks at you closely and his eyes light up.] Ah! I see you have sub-machine gun. [He gazes longingly at the weapon.] We had one once, but Sulik always be hogging it. Got lost in a battle. Such a pity. My magic would be fearsome strong if I had a soul-taker such as that.}
{401}{}{If you want this one, you can have it. I’m sure I’ll find another. [Hand Marli the SMG.]}
{402}{}{Just take it. I don’t even want it after the eye raping you’re giving it. [Hand Marli the SMG.]}
{403}{}{Yeah, I bet. Anyway, me and my soul-taker are going elsewhere now.}
{404}{}{You keep your magic to yourself, pal. Bye.}

{410}{}{[He grins like a maniac as he looks over the weapon.] Oh, you be a good friend to Marli, outworlder. Here, was saving this sweet bubble-water, but I think you should be having it. [He hands you a Nuka-Cola.] Now I be off to spit fiery death at some geckos. [He runs off to the hunting grounds.]}
{411}{}{My magic be fearsome now!}


